[package]
name = "httpsloth"
version = "1.0.0"
edition = "2018"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
clap = "2"
tokio = "0.2.0-alpha.6"
tokio-rustls = "0.12.0-alpha.8"
url = "2"
webpki-roots = "0"