[package]
name = "httpsloth"
version = "2.0.0-alpha.2"
edition = "2018"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
clap = "2"
native-tls = "0.2"
tokio = { version = "0.2", features = ["full"] }
tokio-tls = "0.3.0"
url = "2"