[package]
name = "httpsloth"
version = "0.1.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
native-tls = "0.1"

futures = "0.1"
futures-cpupool = "0.1"
#tokio-core = "0.1"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
#tokio-timer = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
