[package]
name = "httpsloth"
version = "0.2.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
url = "1.5"
native-tls = "0.1"

futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
tokio-tls = "0.1"