[package]
name = "httpsloth"
version = "1.0.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
clap = "2"
futures = "0.1"
tokio = "0.1"
tokio-timer = "0.2"
tokio-rustls = "0.10"
url = "2"
webpki-roots = "0"