[package]
name = "httpsloth"
version = "0.1.0"
authors = ["Andrey Voronkov <voronkovaa@gmail.com>"]

[dependencies]
futures    = "0.1"
native-tls = "0.1"
tokio-core = "0.1"
tokio-io   = "0.1"
tokio-tls  = "0.1"
